from typing import Protocol, Any
from src.mockingbird.datacls import Message

class Model(Protocol):
    def __init__(self, examples: list[Message], *args, **kwargs): ...

    def _build_system_message(examples: list[Message]) -> dict[str, str]: ...

    def _generate(self, messages: list[dict[str, str]], *args, **kwargs) -> Any: ...

    def converse(self) -> None: ...